### ISSUE TITLE
expectAnything doesn't work on Errors

### ISSUE THREAD

**Issue by flash1293** [alfateam/a_mock#14]
My testcase is throwing a `Mock Error: Unexpected arguments` when I pass an `Error` object to a mock-object with `expectAnything()` called.

**Comment by lroal** [comment]
Thanks for reporting it. I am not able to reproduce it though. Do you have a sample ? I tried this, and it doesn't throw:
	var b = mock();
	b.expectAnything();
	b(new Error('some error'));

**Comment by lroal** [comment]
Could it be that you are sending more arguments than one ? ExpectAnything will only accept one argument. E.g if you want to two arguments, you need to do like this:
	var b = mock();
	b.expectAnything().expectAnything();
	b(new Error('some error'), 'foo');

**Comment by flash1293** [comment]
Indeed, that's the problem. Is there a possibility accept all possible inputs?

**Comment by lroal** [comment]
Yes, I think we should change the behaviour to accept all possible input - any number of arguments.
