### ISSUE TITLE
expectAnything doesn't accept nothing

### ISSUE THREAD

**Issue by flash1293** [alfateam/a_mock#15]
`expectAnything`-mocks throw an exception when you call them without any parameters.

**Comment by lroal** [comment]
That is actually intended. ExpectAnything means it will expect one argument, but not care about equality / type of argument. If you want to expect zero arguments, do this:
var b = mock();
b.expect();
b(); //wil return undefined

The semantics of expectAnything can be a bit confusing. Maybe I should redesign the expectAnything to also ignore number of arguments...and use ignore() instead to expect a single argument of any type.

**Comment by flash1293** [comment]
See #14
