### ISSUE TITLE
How to .expect({}) ?

### ISSUE THREAD

**Issue by graingert** [alfateam/a_mock#16]
The documentation seems to indicate that .expect({}) 'will never happen'. Why is this?

```js
> const mock = require('a_mock/mock');
undefined
> m = mock()
{ [Function: mock]
  expect: [Function],
  expectAnything: [Function],
  ignore: [Function],
  reset: [Function],
  verify: [Function],
  expectArray: [Function] }
> m.expect({a: 2})
{ expect: [Function],
  expectAnything: [Function],
  ignore: [Function],
  expectArray: [Function],
  return: [Function],
  whenCalled: [Function],
  repeat: [Function],
  throw: [Function],
  repeatAny: [Function] }
> m.expect({})
{ expect: [Function],
  expectAnything: [Function],
  ignore: [Function],
  expectArray: [Function],
  return: [Function],
  whenCalled: [Function],
  repeat: [Function],
  throw: [Function],
  repeatAny: [Function] }
> m({a: 2})
undefined
> m({})
Mock Error: Unexpected arguments: [object Object].
    at repl:1:1
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:427:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

**Comment by lroal** [comment]
The argument is considered equal when all the leaf nodes of the objects are equal. {} and {} are compared by reference and therefore not equal. But {a: 1} and {a: 1} are equal because the properties 'a' and 'a' have the same value. Another example {a: 1, b: {} } and {a: 1, b: {} } are not equal because the properties 'b' are not equal (compared by reference).

I did this for practial reasons. This might be slightly confusing if you are used to deepEqual from assert.
Do you think it will be a problem ? Or very confusing ?

**Comment by lroal** [comment]
In others word, expecting {} will only succeed if you receive the {} by reference. I can see this will be a problem in those cases when you actually want an empty object - but not by reference.

**Comment by lroal** [comment]
> const mock = require('a').mock;
undefined
> var m = mock();
undefined
> var arg = {};
undefined
> m.expect(arg);
{ expect: [Function],
  expectAnything: [Function],
  ignore: [Function],
  expectArray: [Function],
  return: [Function],
  whenCalled: [Function],
  repeat: [Function],
  throw: [Function],
  repeatAny: [Function] }
> m(arg);
undefined
>

**Comment by graingert** [comment]
I presume this will also not work for `.expect({ empty: {} )`

**Comment by lroal** [comment]
You are correct.
